### ISSUE TITLE
Add some interactivity to the button

### ISSUE THREAD

**Issue by Ma7eer** [HalimaHamood/Random_Colors#4]
Currently, the button state does not change as we click on it. It looks the same. There is no indication when we are hovering on it or when we click on it. 

Add styling that shows when the button is clicked on and or when it is hovered on.

**Comment by HalimaHamood** [comment]
> Currently, the button state does not change as we click on it. It looks the same. There is no indication when we are hovering on it or when we click on it.

> I didn't get ur point, cuz if u don't click on it, the background color will not change.
but if u want me to add hover, it's ok, I will do that.

**Comment by Ma7eer** [comment]
This is what I mean.

Your button should have an effect when a user hovers over it:

![capture](https://user-images.githubusercontent.com/31871338/105746518-f65d4300-5f58-11eb-9e7d-5e1e06b6b9e7.gif)

Also, consider adding an effect when a user clicks on the button as well:

![capture](https://user-images.githubusercontent.com/31871338/105746611-1987f280-5f59-11eb-8a1a-c4648005f495.gif)

Note that the style does not have to be like the ones I am showing above. You can pick what you want.

**Comment by HalimaHamood** [comment]
got it👌
